Implementation;Compile;RootName:TOP
HelpInfo,C:\Microsemi\Libero_SoC_PolarFire_v2.2\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_PolarFire_v2.2\SynplifyPro\bin\mbin\assistant
Implementation;Place and Route;RootName:TOP
Implementation;Place and Route||(null)||Please refer to the log file for details about 7 Info(s)||TOP_layout_log.log;liberoaction://open_report/file/TOP_layout_log.log||(null);(null)
Implementation;Generate Bitstream||(null)||Please refer to the log file for details||TOP_generateBitstream.log;liberoaction://open_report/file/TOP_generateBitstream.log||(null);(null)
Implementation;Generate Bitstream;RootName:TOP
