set_family {PolarFire}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\CCC_100MHz\CCC_100MHz_0\CCC_100MHz_CCC_100MHz_0_PF_CCC.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\CCC_100MHz\CCC_100MHz.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Init_Monitor\Init_Monitor_0\Init_Monitor_Init_Monitor_0_PF_INIT_MONITOR.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Init_Monitor\Init_Monitor.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\RCOSC\RCOSC_0\RCOSC_RCOSC_0_PF_OSC.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\RCOSC\RCOSC.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\hdl\reset_synchronizer.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\CLOCKS_RESETS\CLOCKS_RESETS.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite_addrdec.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite_defaultslavesm.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite_masterstage.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite_slavearbiter.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite_slavestage.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite_matrix4x16.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\AHB_MMIO\AHB_MMIO.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_ahbtoapbsm.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_apbaddrdata.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_penablescheduler.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\AHBtoAPB\AHBtoAPB.v}
read_verilog -mode verilog_2k -lib COREAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core\coreapb3_muxptob3.v}
read_verilog -mode verilog_2k -lib COREAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core\coreapb3_iaddr_reg.v}
read_verilog -mode verilog_2k -lib COREAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core\coreapb3.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\APB_PERIPHERALS\APB_PERIPHERALS.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\spi_clockmux.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\spi_chanctrl.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\spi_control.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\spi_fifo.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\spi_rf.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\spi.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\corespi.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\CoreSPI_0\CoreSPI_0.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\CoreGPIO\3.1.101\rtl\vlog\core\coregpio.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\GPIO\GPIO.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\LSRAM_64kBytes\COREAHBLSRAM_PF_0\rtl\vlog\core\CoreAHBLSRAM_AHBLSramIf.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\LSRAM_64kBytes\COREAHBLSRAM_PF_0\rtl\vlog\core\CoreAHBLSRAM_SramCtrlIf.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\LSRAM_64kBytes\COREAHBLSRAM_PF_0\rtl\vlog\core\CoreAHBLSRAM_PF.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\LSRAM_64kBytes\PF_TPSRAM_AHB_AXI_0\LSRAM_64kBytes_PF_TPSRAM_AHB_AXI_0_PF_TPSRAM.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\LSRAM_64kBytes\LSRAM_64kBytes.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\UART\UART_0\rtl\vlog\core\Clock_gen.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\UART\UART_0\rtl\vlog\core\Rx_async.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\UART\UART_0\rtl\vlog\core\Tx_async.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\UART\UART_0\rtl\vlog\core\fifo_256x8_g5.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\UART\UART_0\rtl\vlog\core\CoreUART.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\UART\UART_0\rtl\vlog\core\CoreUARTapb.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\UART\UART.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\IO\IO.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\MasterAddressDecoder.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\DependenceChecker.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\BitScan0.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\TransactionController.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\MasterControl.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\RoundRobinArb.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\TargetMuxController.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\AddressController.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\Revision.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\DERR_Slave.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\DualPort_FF_SyncWr_SyncRd.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\DualPort_Ram_SyncWr_SyncRd.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\RdFifoDualPort.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\ReadDataMux.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\RequestQual.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\ReadDataController.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\RDataController.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\SlaveDataMuxController.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\RespController.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\FifoDualPort.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\WriteDataMux.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\WDataController.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\Axi4CrossBar.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\AHB_SM.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\MstrAHBtoAXI4Converter.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\Bin2Gray.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\CDC_grayCodeCounter.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\CDC_rdCtrl.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\CDC_wrCtrl.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\RAM_BLOCK.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\CDC_FIFO.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\MstrClockDomainCrossing.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_DownConv_CmdFifoWriteCtrl.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\Axi4Convertors\Hold_Reg_Ctrl.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\Axi4Convertors\DWC_DownConv_Hold_Reg_Rd.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_DownConv_preCalcCmdFifoWrCtrl.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_DownConv_widthConvrd.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\FIFO_CTRL.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\FIFO.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\byte2bit.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_DownConv_readWidthConv.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\Axi4Convertors\DWC_DownConv_Hold_Reg_Wr.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_DownConv_widthConvwr.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_brespCtrl.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_DownConv_writeWidthConv.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DownConverter.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_UpConv_AChannel.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_UpConv_BChannel.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_UpConv_RChan_Ctrl.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_UpConv_preCalcRChan_Ctrl.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\FIFO_downsizing.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_UpConv_RChannel.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_UpConv_WChan_Hold_Reg.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_UpConv_WChan_ReadDataFifoCtrl.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_UpConv_Wchan_WriteDataFifoCtrl.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\FIFO_upsizing.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_UpConv_WChannel.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\DWC_UpConv_preCalcAChannel.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\UpConverter.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\MstrDataWidthConv.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\MstrProtocolConverter.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\RegSliceFull.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\RegisterSlice.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4CrossBar\ResetSycnc.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\MasterConvertor.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\SlvClockDomainCrossing.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\SlvDataWidthConverter.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\SlvAxi4ProtConvAXI4ID.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\SlvAxi4ProtConvRead.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\SlvAxi4ProtConvWrite.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\SlvAxi4ProtocolConv.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\SlvProtocolConverter.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\Axi4Convertors\SlaveConvertor.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREAXI4INTERCONNECT\2.5.100\rtl\vlog\core\CoreAxi4Interconnect.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\AXI_INTERCONNECT\AXI_INTERCONNECT.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3\CCC_0\DDR3_CCC_0_PF_CCC.v}
 add_include_path  {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3\DDRCTRL_0}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3\DDRCTRL_0\CoreDDRMemCtrlr_0.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\ram_simple_dp.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\FIFO_BLK.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\LANE_CTRL.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\LANE_ALIGNMENT.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\APB_IF.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\DLL_MON.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\DELAY_CTRL.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\APB_IOG_CTRL_SM.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\IOG_IF.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\dq_align_dqs_optimization.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\gate_training.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\RDLVL_TRAIN.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\RDLVL_SMS.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\RDLVL.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\TRN_COMPLETE.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\VREF_TR.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\WRLVL_BOT.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\WRLVL.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\LEVELLING.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\PHY_SIG_MOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\flag_generator.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\trn_bclksclk.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\trn_cmdaddr.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\trn_dqsw.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\TRN_CLK.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\ddr4_vref.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\write_callibrator.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\TIP_CTRL_BLK.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\ddr_init_iterator.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\CoreDDR_TIP_INT.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREDDR_TIP\1.5.100\rtl\vlog\core\CoreDDR_TIP_SYN.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_A_11_0\DDR3_DDRPHY_BLK_IOD_A_11_0_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_A_12\DDR3_DDRPHY_BLK_IOD_A_12_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_A_13\DDR3_DDRPHY_BLK_IOD_A_13_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_A_14\DDR3_DDRPHY_BLK_IOD_A_14_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_A_15\DDR3_DDRPHY_BLK_IOD_A_15_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_BA\DDR3_DDRPHY_BLK_IOD_BA_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_BCLK_TRAINING\DDR3_DDRPHY_BLK_IOD_BCLK_TRAINING_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_CAS_N\DDR3_DDRPHY_BLK_IOD_CAS_N_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_CKE\DDR3_DDRPHY_BLK_IOD_CKE_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_CS_N\DDR3_DDRPHY_BLK_IOD_CS_N_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_ODT\DDR3_DDRPHY_BLK_IOD_ODT_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_RAS_N\DDR3_DDRPHY_BLK_IOD_RAS_N_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_REF_CLK_TRAINING\DDR3_DDRPHY_BLK_IOD_REF_CLK_TRAINING_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_RESET_N\DDR3_DDRPHY_BLK_IOD_RESET_N_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\IOD_WE_N\DDR3_DDRPHY_BLK_IOD_WE_N_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\LANECTRL_ADDR_CMD_0\DDR3_DDRPHY_BLK_LANECTRL_ADDR_CMD_0_PF_LANECTRL.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\LANE_0_CTRL\DDR3_DDRPHY_BLK_LANE_0_CTRL_PF_LANECTRL.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\LANE_0_IOD_DM\DDR3_DDRPHY_BLK_LANE_0_IOD_DM_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\LANE_0_IOD_DQSW_TRAINING\DDR3_DDRPHY_BLK_LANE_0_IOD_DQSW_TRAINING_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\LANE_0_IOD_DQS\DDR3_DDRPHY_BLK_LANE_0_IOD_DQS_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\LANE_0_IOD_DQ\DDR3_DDRPHY_BLK_LANE_0_IOD_DQ_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\LANE_0_IOD_READ_TRAINING\DDR3_DDRPHY_BLK_LANE_0_IOD_READ_TRAINING_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\LANE_1_CTRL\DDR3_DDRPHY_BLK_LANE_1_CTRL_PF_LANECTRL.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\LANE_1_IOD_DM\DDR3_DDRPHY_BLK_LANE_1_IOD_DM_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\LANE_1_IOD_DQSW_TRAINING\DDR3_DDRPHY_BLK_LANE_1_IOD_DQSW_TRAINING_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\LANE_1_IOD_DQS\DDR3_DDRPHY_BLK_LANE_1_IOD_DQS_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\LANE_1_IOD_DQ\DDR3_DDRPHY_BLK_LANE_1_IOD_DQ_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\LANE_1_IOD_READ_TRAINING\DDR3_DDRPHY_BLK_LANE_1_IOD_READ_TRAINING_PF_IOD.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3_DDRPHY_BLK\DDR3_DDRPHY_BLK.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3\DLL_0\DDR3_DLL_0_PF_CCC.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\SgCore\PF_DDR_CFG_INIT\1.0.100\cfg_init.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\DDR3\DDR3.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\MEMORY\MEMORY.v}
read_verilog -mode verilog_2k -lib COREJTAGDEBUG_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREJTAGDEBUG\2.0.100\rtl\vlog\core\corejtagdebug_uj_jtag.v}
read_verilog -mode verilog_2k -lib COREJTAGDEBUG_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\Actel\DirectCore\COREJTAGDEBUG\2.0.100\rtl\vlog\core\corejtagdebug.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\JTAG_DEBUG\JTAG_DEBUG.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_coreplex_local_interrupter_clint.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_capture_chain.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_capture_update_chain.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_capture_update_chain_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_jtag_bypass_chain.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_capture_update_chain_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg_vec_90.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_jtag_state_machine.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_negative_edge_latch.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_negative_edge_latch_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_jtag_tap_controller.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_debug_transport_module_jtag.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xbar.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xbar_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xbar_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xing.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg_vec_89.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_reset_catch_and_sync.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xbar_int_xbar.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xing_xing.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_amoalu.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_arbiter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_arbiter_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_d_cache_data_array.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_pmp_checker.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tlb.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_d_cache_dcache.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_i_cache_icache.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_shift_queue.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tlb_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_frontend_frontend.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_hella_cache_arbiter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_rr_arbiter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_ptw.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_alu.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_breakpoint_unit.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_csr_file.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_rvc_expander.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_i_buf.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_mul_div.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_rocket.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_tile_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_rocket_tile_rocket.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_sync_rocket_tile_tile.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tlfifo_fixer_system_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_level_gateway.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_13.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tlplic_plic.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_atomic_automata.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_4.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_5.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_6.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_7.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_8.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_10.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_9.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_3.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_4.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_23.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_24.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_25.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_26.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_27.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_error.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_14.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_15.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_16.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_17.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_18.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_system_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_cache_cork.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg_vec_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_3.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_4.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_5.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_sink_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_sink_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_source_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_async_crossing_sink.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_inner_dm_inner.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_inner_async_dm_inner.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_source_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_dmi_to_tl_dmi2tl.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_sink.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_source.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_async_crossing_source_dm_inner.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg_vec.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_outer_dm_outer.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_dmi_xbar.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_outer_async_dm_outer.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_debug.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_21.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_22.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_error_error.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_filter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_repeater.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_repeater_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_fragmenter_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_splitter_system_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_20.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_to_ahb.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_19.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_to_ahb_converter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_width_widget.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_width_widget_3.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_memory_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_periphery_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_system_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_core_risc_vahb_top.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\Mi_V_Processor\Mi_V_Processor.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\PROCESSOR\PROCESSOR.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\component\work\TOP\TOP.v}
set_top_level {TOP}
map_netlist
read_sdc {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\constraint\TOP_derived_constraints.sdc}
check_constraints {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\constraint\synthesis_sdc_errors.log}
write_fdc {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_everest2_ddr\designer\TOP\synthesis.fdc}
