set_family {PolarFire}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\CCC_100MHz\CCC_100MHz_0\CCC_100MHz_CCC_100MHz_0_PF_CCC.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\CCC_100MHz\CCC_100MHz.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Init_Monitor\Init_Monitor_0\Init_Monitor_Init_Monitor_0_PF_INIT_MONITOR.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Init_Monitor\Init_Monitor.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\RCOSC\RCOSC_0\RCOSC_RCOSC_0_PF_OSC.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\RCOSC\RCOSC.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\hdl\reset_synchronizer.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\CLOCKS_RESETS\CLOCKS_RESETS.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CoreAHBLite\5.3.101\rtl\vlog\core\coreahblite_addrdec.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CoreAHBLite\5.3.101\rtl\vlog\core\coreahblite_defaultslavesm.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CoreAHBLite\5.3.101\rtl\vlog\core\coreahblite_masterstage.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CoreAHBLite\5.3.101\rtl\vlog\core\coreahblite_slavearbiter.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CoreAHBLite\5.3.101\rtl\vlog\core\coreahblite_slavestage.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CoreAHBLite\5.3.101\rtl\vlog\core\coreahblite_matrix4x16.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\AHB_MMIO\AHB_MMIO.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_ahbtoapbsm.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_apbaddrdata.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_penablescheduler.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\AHBtoAPB\AHBtoAPB.v}
read_verilog -mode verilog_2k -lib COREAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core\coreapb3_muxptob3.v}
read_verilog -mode verilog_2k -lib COREAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core\coreapb3_iaddr_reg.v}
read_verilog -mode verilog_2k -lib COREAPB3_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core\coreapb3.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\APB_PERIPHERALS\APB_PERIPHERALS.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\spi_clockmux.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\spi_chanctrl.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\spi_control.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\spi_fifo.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\spi_rf.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\spi.v}
read_verilog -mode verilog_2k -lib CORESPI_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CORESPI\5.2.104\rtl\vlog\core\corespi.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\CoreSPI_0\CoreSPI_0.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\CoreGPIO\3.1.101\rtl\vlog\core\coregpio.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\GPIO\GPIO.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\LSRAM_64kBytes\COREAHBLSRAM_PF_0\rtl\vlog\core\CoreAHBLSRAM_AHBLSramIf.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\LSRAM_64kBytes\COREAHBLSRAM_PF_0\rtl\vlog\core\CoreAHBLSRAM_SramCtrlIf.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\LSRAM_64kBytes\COREAHBLSRAM_PF_0\rtl\vlog\core\CoreAHBLSRAM_PF.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\LSRAM_64kBytes\PF_TPSRAM_AHB_AXI_0\LSRAM_64kBytes_PF_TPSRAM_AHB_AXI_0_PF_TPSRAM.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\LSRAM_64kBytes\LSRAM_64kBytes.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\UART\UART_0\rtl\vlog\core\Clock_gen.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\UART\UART_0\rtl\vlog\core\Rx_async.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\UART\UART_0\rtl\vlog\core\Tx_async.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\UART\UART_0\rtl\vlog\core\fifo_256x8_g5.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\UART\UART_0\rtl\vlog\core\CoreUART.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\UART\UART_0\rtl\vlog\core\CoreUARTapb.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\UART\UART.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\IO\IO.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\AHB\AHB_0\rtl\vlog\core\coreahblite.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\AHB\AHB.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\LSRAM_code\COREAHBLSRAM_PF_0\rtl\vlog\core\CoreAHBLSRAM_AHBLSramIf.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\LSRAM_code\COREAHBLSRAM_PF_0\rtl\vlog\core\CoreAHBLSRAM_SramCtrlIf.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\LSRAM_code\COREAHBLSRAM_PF_0\rtl\vlog\core\CoreAHBLSRAM_PF.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\LSRAM_code\PF_TPSRAM_AHB_AXI_0\LSRAM_code_PF_TPSRAM_AHB_AXI_0_PF_TPSRAM.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\LSRAM_code\LSRAM_code.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\MEMORY2\MEMORY2.v}
read_verilog -mode verilog_2k -lib COREJTAGDEBUG_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\COREJTAGDEBUG\2.0.100\rtl\vlog\core\corejtagdebug_uj_jtag.v}
read_verilog -mode verilog_2k -lib COREJTAGDEBUG_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\Actel\DirectCore\COREJTAGDEBUG\2.0.100\rtl\vlog\core\corejtagdebug.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\JTAG_DEBUG\JTAG_DEBUG.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_coreplex_local_interrupter_clint.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_capture_chain.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_capture_update_chain.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_capture_update_chain_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_jtag_bypass_chain.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_capture_update_chain_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg_vec_90.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_jtag_state_machine.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_negative_edge_latch.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_negative_edge_latch_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_jtag_tap_controller.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_debug_transport_module_jtag.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xbar.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xbar_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xbar_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xing.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg_vec_89.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_reset_catch_and_sync.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xbar_int_xbar.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_int_xing_xing.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_amoalu.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_arbiter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_arbiter_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_d_cache_data_array.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_pmp_checker.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tlb.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_d_cache_dcache.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_i_cache_icache.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_shift_queue.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tlb_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_frontend_frontend.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_hella_cache_arbiter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_rr_arbiter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_ptw.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_alu.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_breakpoint_unit.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_csr_file.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_rvc_expander.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_i_buf.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_mul_div.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_rocket.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_tile_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_rocket_tile_rocket.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_sync_rocket_tile_tile.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tlfifo_fixer_system_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_level_gateway.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_13.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tlplic_plic.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_atomic_automata.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_4.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_5.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_6.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_7.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_8.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_10.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_9.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_3.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_4.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_23.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_24.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_25.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_26.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_27.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_error.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_14.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_15.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_16.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_17.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_18.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_buffer_system_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_cache_cork.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg_vec_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_3.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_4.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_5.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_sink_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_sink_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_valid_sync_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_source_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_async_crossing_sink.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_inner_dm_inner.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_inner_async_dm_inner.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_source_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_dmi_to_tl_dmi2tl.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_sink.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_queue_source.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_async_crossing_source_dm_inner.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_async_reset_reg_vec.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_outer_dm_outer.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_dmi_xbar.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_outer_async_dm_outer.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_debug_module_debug.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_21.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_22.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_error_error.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_filter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_repeater.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_repeater_2.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_fragmenter_1.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_splitter_system_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_20.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_to_ahb.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_queue_19.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_to_ahb_converter.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_width_widget.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_width_widget_3.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_memory_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_periphery_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_tl_xbar_system_bus.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb_core_risc_vahb_top.v}
read_verilog -mode verilog_2k -lib CORERISCVRV32IMA_LIB {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor_0\rtl\vlog\core\miv_rv32ima_l1_ahb.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\Mi_V_Processor\Mi_V_Processor.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\PROCESSOR\PROCESSOR.v}
read_verilog -mode verilog_2k {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\component\work\TOP\TOP.v}
set_top_level {TOP}
map_netlist
read_sdc {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\constraint\TOP_derived_constraints.sdc}
check_constraints {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\constraint\synthesis_sdc_errors.log}
write_fdc {C:\Microsemiprj_PF\apps\riscv_bootloader\UART_2_SCSPI_Bridge_eval2_sram\designer\TOP\synthesis.fdc}
